version: '3.8'

services:
  thinking-service:
    build:
      context: ./Thinking
    container_name: thinking-service
    ports:
      - "7000:7000"
    env_file:
      - ./SharedData/config.env      
    volumes:
      - /etc/models:/etc/models
      - ./SharedData:/app/SharedData
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    networks:
      - homeassist-net

  speaking-service:
    build:
      context: ./Speaking
    container_name: speaking-service
    ports:
      - "9001:9001"
    env_file:
      - ./SharedData/config.env      
    volumes:
      - /etc/models:/etc/models
      - ./SharedData:/app/SharedData
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    networks:
      - homeassist-net

  hearing-service:
    build:
      context: ./Hearing
    container_name: hearing-service
    ports:
      - "8000:8000"
    env_file:
      - ./SharedData/config.env      
    volumes:
      - /etc/models:/etc/models
      - ./SharedData:/app/SharedData
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    networks:
      - homeassist-net

networks:
  homeassist-net:
    name: homeassist-net
    driver: bridge